#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""LocalAgent 的最小运行时上下文基础组件。"""

from core.runtime.cancellation import CancellationReason, CancellationSource, CancellationToken, RunCancelledError
from core.runtime.run_registry import RunHandle, RunRegistry, process_run_registry
from core.runtime.timeout import OperationTimeoutError, OperationType, effective_timeout_seconds

from core.runtime.state import (
    AGENT_STATE_SCHEMA_VERSION,
    AgentState,
    AgentStateValidationError,
    RunStatus,
    StepState,
    StepStatus,
    StopReason,
    UnsupportedStateVersionError,
)
from core.runtime.context import (
    Clock,
    Deadline,
    LEGACY_DEFAULT_SESSION_ID,
    RunContext,
    RunContextData,
    RunDeadlineExceededError,
    RunIdentifiers,
    SystemClock,
    create_run_context,
)
from core.runtime.agent_loop import (
    ActionOutcome,
    AgentAction,
    AgentLoop,
    AgentLoopDriver,
    AgentLoopPolicy,
    AgentObservation,
    LEGACY_AGENT_ROUTER_STEP_ID,
    LEGACY_AGENT_ROUTER_STEP_NAME,
    LegacyAgentRouterDriver,
)
from core.runtime.model_context import (
    ContextBuilder, ContextBuildRequest, ContextBuildResult, ContextBudgetExceededError, ContextDropRecord,
    ContextItem, ContextSourceType, ContextStats, ContextTrustLevel, DeterministicTokenEstimator,
    MemoryContextRecord, MemoryProvenance, ModelContextRequirements, TokenEstimator,
)
from core.runtime.planning import Plan, PlanSource, PlanStep, PlanValidator, RiskLevel, TaskCapabilityRequirements, create_single_step_plan
from core.runtime.plan_graph import PlanGraph, PlanGraphValidationError, PlanGraphValidator
from core.runtime.model_selection import (ModelCostProfile, ModelPreference, ModelProfile, ModelProfileId, ModelResolver, ModelSelectionDecision, ModelSelectionError, ModelSelectionObjective, ModelSelectionPolicy, ModelSelectionReason, ModelSelectionRequest)
from core.runtime.state_machine import (
    AgentStateMachine,
    InvalidStateTransitionError,
    RunEventType,
    RunStateEvent,
    StepEventType,
    StepStateEvent,
)
from core.runtime.scheduler import (
    SchedulerClaimError,
    SchedulerError,
    SchedulerPlanStateMismatchError,
    SchedulerSnapshot,
    SerialScheduler,
    StepClaim,
)
from core.runtime.run_coordinator import (
    RunCoordinator,
    RunCoordinatorError,
    RunCoordinatorResult,
    RunFinalizationDecision,
)
from core.runtime.events import (
    RUNTIME_EVENT_SCHEMA_VERSION,
    BudgetExhaustedPayload,
    CancellationPayload,
    ErrorPayload,
    ModelCompletedPayload,
    ModelStartedPayload,
    OutputDeltaPayload,
    RunCompletedPayload,
    RunStartedPayload,
    RetrievalBudgetPayload,
    RetrievalCompletedPayload,
    RetrievalStageCompletedPayload,
    RetrievalStartedPayload,
    RuntimeEvent,
    RuntimeEventDraft,
    RuntimeEventPayload,
    RuntimeEventType,
    StepCompletedPayload,
    StepStartedPayload,
    ToolCompletedPayload,
    ToolStartedPayload,
    TimeoutPayload,
)
from core.runtime.event_channel import (
    EventChannelClosedError,
    EventChannelState,
    RuntimeEventChannel,
)
from core.runtime.event_emitter import (
    EventEmitterSyncError,
    RunEventEmitter,
    StepEventEmitter,
)
from core.runtime.event_journal import (
    JOURNAL_SCHEMA_VERSION,
    JournalAppendStatus,
    JournalError,
    JournalErrorCode,
    JournalRecord,
    RunEventJournal,
)
from core.runtime.event_journal_store import (
    InMemoryRunEventJournal,
    SQLiteRunEventJournal,
)
from core.runtime.event_consumer import (
    ConsumerErrorCode,
    EventConsumptionCheckpoint,
    EventConsumptionCheckpointStore,
    EventConsumptionStatus,
    EventConsumerError,
    IdempotentEventConsumer,
    InMemoryEventConsumptionCheckpointStore,
    SQLiteEventConsumptionCheckpointStore,
)
from core.runtime.stream_adapter import RuntimeEventTextAdapter

__all__ = [
    "AGENT_STATE_SCHEMA_VERSION",
    "ActionOutcome",
    "AgentAction",
    "AgentLoop",
    "AgentLoopDriver",
    "AgentLoopPolicy",
    "AgentObservation",
    "AgentState",
    "AgentStateMachine",
    "AgentStateValidationError",
    "CancellationSource",
    "CancellationReason", "RunHandle", "RunRegistry", "process_run_registry",
    "OperationTimeoutError", "OperationType", "effective_timeout_seconds",
    "ContextBuilder", "ContextBuildRequest", "ContextBuildResult", "ContextBudgetExceededError",
    "ContextDropRecord", "ContextItem", "ContextSourceType", "ContextStats", "ContextTrustLevel",
    "DeterministicTokenEstimator", "MemoryContextRecord", "MemoryProvenance",
    "ModelContextRequirements", "TokenEstimator",
    "Plan", "PlanSource", "PlanStep", "PlanValidator", "RiskLevel", "TaskCapabilityRequirements", "create_single_step_plan",
    "PlanGraph", "PlanGraphValidationError", "PlanGraphValidator",
    "ModelCostProfile", "ModelPreference", "ModelProfile", "ModelProfileId", "ModelResolver", "ModelSelectionDecision", "ModelSelectionError", "ModelSelectionObjective", "ModelSelectionPolicy", "ModelSelectionReason", "ModelSelectionRequest",
    "CancellationToken",
    "Clock",
    "Deadline",
    "LEGACY_DEFAULT_SESSION_ID",
    "LEGACY_AGENT_ROUTER_STEP_ID",
    "LEGACY_AGENT_ROUTER_STEP_NAME",
    "LegacyAgentRouterDriver",
    "InvalidStateTransitionError",
    "RunCancelledError",
    "RunContext",
    "RunCoordinator",
    "RunCoordinatorError",
    "RunCoordinatorResult",
    "RunContextData",
    "RunDeadlineExceededError",
    "RunIdentifiers",
    "RunStatus",
    "RunEventType",
    "RunStateEvent",
    "RunFinalizationDecision",
    "SchedulerClaimError",
    "SchedulerError",
    "SchedulerPlanStateMismatchError",
    "SchedulerSnapshot",
    "SerialScheduler",
    "StepClaim",
    "StepEventType",
    "StepState",
    "StepStateEvent",
    "StepStatus",
    "StopReason",
    "UnsupportedStateVersionError",
    "RUNTIME_EVENT_SCHEMA_VERSION",
    "BudgetExhaustedPayload",
    "CancellationPayload",
    "ErrorPayload",
    "EventChannelClosedError",
    "EventChannelState",
    "EventConsumptionCheckpoint",
    "EventConsumptionCheckpointStore",
    "EventConsumptionStatus",
    "EventConsumerError",
    "EventEmitterSyncError",
    "ConsumerErrorCode",
    "IdempotentEventConsumer",
    "InMemoryEventConsumptionCheckpointStore",
    "InMemoryRunEventJournal",
    "JOURNAL_SCHEMA_VERSION",
    "JournalAppendStatus",
    "JournalError",
    "JournalErrorCode",
    "JournalRecord",
    "ModelCompletedPayload",
    "ModelStartedPayload",
    "OutputDeltaPayload",
    "RunCompletedPayload",
    "RunEventEmitter",
    "RunStartedPayload",
    "RetrievalBudgetPayload",
    "RetrievalCompletedPayload",
    "RetrievalStageCompletedPayload",
    "RetrievalStartedPayload",
    "RuntimeEvent",
    "RuntimeEventChannel",
    "RuntimeEventDraft",
    "RuntimeEventPayload",
    "RuntimeEventTextAdapter",
    "RuntimeEventType",
    "RunEventJournal",
    "SQLiteEventConsumptionCheckpointStore",
    "SQLiteRunEventJournal",
    "StepCompletedPayload",
    "StepEventEmitter",
    "StepStartedPayload",
    "ToolCompletedPayload",
    "ToolStartedPayload",
    "TimeoutPayload",
    "SystemClock",
    "create_run_context",
]

from core.runtime.observability import (
    NoopRuntimeGaugeProvider,
    NoopRuntimeInfrastructureMetricsHook,
    ObservabilityHealth,
    ObservabilityHealthSnapshot,
    RuntimeGaugeProvider,
    RuntimeInfrastructureMetricsHook,
)
from core.runtime.structured_logging import (
    InMemoryStructuredRuntimeLogger,
    JsonStructuredRuntimeLogger,
    NoopStructuredRuntimeLogger,
    RuntimeLogLevel,
    RuntimeLogRecord,
    StructuredLogProjector,
    StructuredRuntimeLogger,
    runtime_log_level,
)
from core.runtime.metrics import (
    ApplicationRuntimeGaugeProvider,
    DEFAULT_RUNTIME_METRIC_REGISTRY,
    InMemoryMetricsRecorder,
    MetricDescriptor,
    MetricLabelPolicy,
    MetricType,
    NoopMetricsRecorder,
    RecorderInfrastructureMetricsHook,
    RUNTIME_METRIC_DESCRIPTORS,
    RuntimeMetricsProjector,
    RuntimeMetricsRecorder,
    RuntimeMetricsCollector,
    RuntimeMetricsSnapshot,
    record_gauge_snapshot,
)
from core.runtime.observability_dispatcher import (
    LOGGER_CONSUMER_ID,
    METRICS_CONSUMER_ID,
    RuntimeObservabilityDispatcher,
)

__all__ += [
    "ApplicationRuntimeGaugeProvider",
    "DEFAULT_RUNTIME_METRIC_REGISTRY",
    "InMemoryMetricsRecorder",
    "InMemoryStructuredRuntimeLogger",
    "JsonStructuredRuntimeLogger",
    "LOGGER_CONSUMER_ID",
    "METRICS_CONSUMER_ID",
    "MetricDescriptor",
    "MetricLabelPolicy",
    "MetricType",
    "NoopMetricsRecorder",
    "NoopRuntimeGaugeProvider",
    "NoopRuntimeInfrastructureMetricsHook",
    "NoopStructuredRuntimeLogger",
    "ObservabilityHealth",
    "ObservabilityHealthSnapshot",
    "RecorderInfrastructureMetricsHook",
    "RUNTIME_METRIC_DESCRIPTORS",
    "RuntimeGaugeProvider",
    "RuntimeInfrastructureMetricsHook",
    "RuntimeLogLevel",
    "RuntimeLogRecord",
    "RuntimeMetricsProjector",
    "RuntimeMetricsRecorder",
    "RuntimeMetricsCollector",
    "RuntimeMetricsSnapshot",
    "RuntimeObservabilityDispatcher",
    "StructuredLogProjector",
    "StructuredRuntimeLogger",
    "record_gauge_snapshot",
    "runtime_log_level",
]

from core.runtime.tracing import (
    DENIED_SPAN_ATTRIBUTES,
    SAFE_SPAN_ATTRIBUTES,
    InMemorySpanRecorder,
    NoopSpanRecorder,
    OpenTelemetryCompatibleSpanAdapter,
    SpanHandle,
    SpanRecord,
    SpanRecorder,
    SpanRecorderHealth,
    SpanStatus,
    TraceContext,
    activate_span,
    current_trace_context,
    current_span_recorder,
)
__all__ += [
    "DENIED_SPAN_ATTRIBUTES", "SAFE_SPAN_ATTRIBUTES", "InMemorySpanRecorder",
    "NoopSpanRecorder", "OpenTelemetryCompatibleSpanAdapter", "SpanHandle",
    "SpanRecord", "SpanRecorder", "SpanRecorderHealth", "SpanStatus", "TraceContext",
    "activate_span", "current_trace_context", "current_span_recorder",
]

from core.runtime.parallel_execution import (
    ParallelExecutionInfrastructureError, ParallelExecutionReport, ParallelExecutor,
    ParallelFailureMode, ParallelExecutionPolicy, StepConcurrencySpec, StepExecutionDriver, StepExecutionMode,
    StepExecutionOutcome,
)

__all__ += [
    "ParallelExecutionInfrastructureError", "ParallelExecutionReport", "ParallelExecutor",
    "ParallelFailureMode", "ParallelExecutionPolicy", "StepConcurrencySpec", "StepExecutionDriver", "StepExecutionMode",
    "StepExecutionOutcome",
]
from core.runtime.budget import BudgetedModelStream, BudgetExceededError, BudgetLedger, BudgetPolicy, BudgetReservation, BudgetReservationError, BudgetSnapshot, BudgetUsage, RunBudget, UsageSource
from core.runtime.blocking_executor import (
    BlockingExecutorAdmissionTimeout,
    BlockingExecutorClosedError,
    BlockingExecutorNestedSubmissionError,
    BlockingExecutorSnapshot,
    BlockingTaskHandle,
    BlockingTaskKind,
    BlockingTaskRecord,
    BlockingTaskState,
    BlockingTaskWaitState,
    BoundedBlockingExecutor,
    DEFAULT_BLOCKING_MAX_PENDING_TASKS,
    DEFAULT_BLOCKING_MAX_WORKERS,
    process_blocking_executor,
)

__all__ += [
    "BudgetedModelStream",
    "BudgetExceededError",
    "BudgetLedger",
    "BudgetPolicy",
    "BudgetReservation",
    "BudgetReservationError",
    "BudgetSnapshot",
    "BudgetUsage",
    "RunBudget",
    "UsageSource",
    "BlockingExecutorAdmissionTimeout",
    "BlockingExecutorClosedError",
    "BlockingExecutorNestedSubmissionError",
    "BlockingExecutorSnapshot",
    "BlockingTaskHandle",
    "BlockingTaskKind",
    "BlockingTaskRecord",
    "BlockingTaskState",
    "BlockingTaskWaitState",
    "BoundedBlockingExecutor",
    "DEFAULT_BLOCKING_MAX_PENDING_TASKS",
    "DEFAULT_BLOCKING_MAX_WORKERS",
    "process_blocking_executor",
]

from core.runtime.circuit_breaker import (
    CircuitOpenError,
    CircuitPermit,
    CircuitPermitStateError,
    ModelCircuitBreaker,
    ModelCircuitBreakerConfig,
    ModelCircuitBreakerRegistry,
    ModelCircuitBreakerSnapshot,
    ModelCircuitState,
)
from core.runtime.model_routing import (
    ModelFailureCategory,
    ModelRoutingCandidate,
    ModelRoutingDecision,
    ModelRoutingError,
    ModelRoutingPolicy,
    RoutingAdjustment,
)
from core.runtime.model_invocation import (
    CircuitHealthOutcome,
    GeneratorModelAdapter,
    ModelAdapter,
    ModelAdapterInvocationError,
    ModelAdapterResolutionError,
    ModelAdapterResolver,
    ModelAdapterResponse,
    ModelInvocationAttempt,
    ModelInvocationChainError,
    ModelInvocationConfirmationRequired,
    ModelInvocationFailure,
    ModelInvocationResult,
    ModelInvocationRouter,
    ModelUsageSource,
    classify_model_failure,
)
from core.runtime.retry import (
    AsyncioSleeper, CancellableRetrySleeper, JitterMode, OperationIdempotency, RandomSource,
    RateLimitRecoveryMode, RetryDecision, RetryExecutor, RetryPolicy,
    RetryableOperationKind, Sleeper, retry_allowed_by_idempotency,
)
from core.runtime.tool_contract import (
    RetryDisposition, ToolErrorCategory, ToolExecutionError, ToolExecutionPhase,
    ToolExecutionResult, ToolExecutionSpec, ToolExecutionStatus, ToolInvocation,
    ToolOutput, ToolOutputValidationError, ToolSideEffectKind, ToolSideEffectState, build_tool_output,
    canonical_json_digest, retry_disposition_for, safe_key_digest, thaw_json,
)
from core.runtime.tool_concurrency import (
    ToolConcurrencyController, ToolResourceAcquireError, ToolResourceLease,
    ToolWorkerRecord,
)
from core.runtime.tool_adapters import (
    ComplexWorkflowToolAdapter, LegacyStringToolAdapter, ToolAdapter,
    ToolAdapterInvocationError, ToolAdapterResponse,
)
from core.runtime.tool_execution import (
    AttemptSideEffectTracker, ToolAttemptExecutor, ToolExecutionContext,
    ToolExecutionFailed, ToolExecutionService,
)

__all__ += [
    "CircuitHealthOutcome",
    "CircuitOpenError",
    "CircuitPermit",
    "CircuitPermitStateError",
    "GeneratorModelAdapter",
    "ModelAdapter",
    "ModelAdapterInvocationError",
    "ModelAdapterResolutionError",
    "ModelAdapterResolver",
    "ModelAdapterResponse",
    "ModelCircuitBreaker",
    "ModelCircuitBreakerConfig",
    "ModelCircuitBreakerRegistry",
    "ModelCircuitBreakerSnapshot",
    "ModelCircuitState",
    "ModelFailureCategory",
    "ModelInvocationAttempt",
    "ModelInvocationChainError",
    "ModelInvocationConfirmationRequired",
    "ModelInvocationFailure",
    "ModelInvocationResult",
    "ModelInvocationRouter",
    "ModelRoutingCandidate",
    "ModelRoutingDecision",
    "ModelRoutingError",
    "ModelRoutingPolicy",
    "ModelUsageSource",
    "RoutingAdjustment",
    "classify_model_failure",
    "AsyncioSleeper", "CancellableRetrySleeper", "JitterMode", "OperationIdempotency", "RandomSource",
    "RateLimitRecoveryMode", "RetryDecision", "RetryExecutor", "RetryPolicy",
    "RetryableOperationKind", "Sleeper", "retry_allowed_by_idempotency",
    "RetryDisposition", "ToolErrorCategory", "ToolExecutionError", "ToolExecutionPhase",
    "ToolExecutionResult", "ToolExecutionSpec", "ToolExecutionStatus", "ToolInvocation",
    "ToolOutput", "ToolOutputValidationError", "ToolSideEffectKind", "ToolSideEffectState", "build_tool_output",
    "canonical_json_digest", "retry_disposition_for", "safe_key_digest", "thaw_json",
    "ToolConcurrencyController", "ToolResourceAcquireError", "ToolResourceLease",
    "ToolWorkerRecord",
    "ComplexWorkflowToolAdapter", "LegacyStringToolAdapter", "ToolAdapter",
    "ToolAdapterInvocationError", "ToolAdapterResponse",
    "AttemptSideEffectTracker", "ToolAttemptExecutor", "ToolExecutionContext",
    "ToolExecutionFailed", "ToolExecutionService",
]

from core.runtime.retrieval_contract import (
    CitationBinding,
    MaterializedDocument,
    QueryRewriteStrategy,
    RetrievalBudgetUsage,
    RetrievalCandidate,
    RetrievalErrorCategory,
    RetrievalExecutionError,
    RetrievalExecutionResult,
    RetrievalExecutionSpec,
    RetrievalExecutionStatus,
    RetrievalInvocation,
    RetrievalProvenance,
    RetrievalStage,
    RetrievalStageRecord,
    RetrievalStageStatus,
    RetrievalTransformation,
    RetrievedChunk,
    SourceMetadata,
    content_digest,
    normalize_query,
    query_digest,
)
from core.runtime.retrieval_context import (
    RetrievalDeadlineExceededError,
    RetrievalExecutionContext,
)
from core.runtime.retrieval_adapters import (
    QueryEmbedding,
    RetrievalAdapter,
    RetrievalAdapterError,
    RuntimeKnowledgeRetrievalAdapter,
)
from core.runtime.retrieval_execution import RetrievalExecutionService
from core.knowledge_base.vector_scores import (
    VectorScoreSemantics,
    normalize_vector_score,
)

__all__ += [
    "CitationBinding",
    "MaterializedDocument",
    "QueryEmbedding",
    "QueryRewriteStrategy",
    "RetrievalAdapter",
    "RetrievalAdapterError",
    "RetrievalBudgetUsage",
    "RetrievalCandidate",
    "RetrievalDeadlineExceededError",
    "RetrievalErrorCategory",
    "RetrievalExecutionContext",
    "RetrievalExecutionError",
    "RetrievalExecutionResult",
    "RetrievalExecutionService",
    "RetrievalExecutionSpec",
    "RetrievalExecutionStatus",
    "RetrievalInvocation",
    "RetrievalProvenance",
    "RetrievalStage",
    "RetrievalStageRecord",
    "RetrievalStageStatus",
    "RetrievalTransformation",
    "RetrievedChunk",
    "RuntimeKnowledgeRetrievalAdapter",
    "SourceMetadata",
    "content_digest",
    "normalize_query",
    "query_digest",
    "VectorScoreSemantics",
    "normalize_vector_score",
]

from core.runtime.plan_fingerprint import PlanFingerprinter
from core.runtime.snapshot_contract import (
    BUDGET_SNAPSHOT_SCHEMA_VERSION,
    PLAN_SNAPSHOT_SCHEMA_VERSION,
    SNAPSHOT_DIGEST_ALGORITHM,
    SNAPSHOT_SCHEMA_VERSION,
    STATE_SNAPSHOT_SCHEMA_VERSION,
    AgentStateSnapshot,
    BudgetSnapshot as SafeBudgetSnapshot,
    PlanSnapshot,
    PlanStepSnapshot,
    RunSnapshot,
    RuntimeMetadata,
    StepStateSnapshot,
    TextSummary,
)
from core.runtime.snapshot_serialization import (
    canonical_json as snapshot_canonical_json,
    snapshot_from_json,
    snapshot_to_json,
)
from core.runtime.snapshot_store import (
    InMemorySnapshotStore,
    SQLiteSnapshotStore,
    SnapshotErrorCode,
    SnapshotSaveStatus,
    SnapshotStore,
    SnapshotStoreError,
)

__all__ += [
    "AgentStateSnapshot",
    "BUDGET_SNAPSHOT_SCHEMA_VERSION",
    "InMemorySnapshotStore",
    "PLAN_SNAPSHOT_SCHEMA_VERSION",
    "PlanFingerprinter",
    "PlanSnapshot",
    "PlanStepSnapshot",
    "RunSnapshot",
    "RuntimeMetadata",
    "SNAPSHOT_DIGEST_ALGORITHM",
    "SNAPSHOT_SCHEMA_VERSION",
    "STATE_SNAPSHOT_SCHEMA_VERSION",
    "SQLiteSnapshotStore",
    "SafeBudgetSnapshot",
    "SnapshotErrorCode",
    "SnapshotSaveStatus",
    "SnapshotStore",
    "SnapshotStoreError",
    "StepStateSnapshot",
    "TextSummary",
    "snapshot_canonical_json",
    "snapshot_from_json",
    "snapshot_to_json",
]
