#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""LocalAgent 的最小运行时上下文基础组件。"""

from core.runtime.cancellation import CancellationReason, CancellationSource, CancellationToken, RunCancelledError
from core.runtime.run_registry import RunHandle, RunRegistry, process_run_registry
from core.runtime.timeout import OperationTimeoutError, OperationType, effective_timeout_seconds

from core.runtime.state import (
    AGENT_STATE_SCHEMA_VERSION,
    AgentState,
    AgentStateValidationError,
    RunStatus,
    StepState,
    StepStatus,
    StopReason,
    UnsupportedStateVersionError,
)
from core.runtime.context import (
    Clock,
    Deadline,
    LEGACY_DEFAULT_SESSION_ID,
    RunContext,
    RunContextData,
    RunDeadlineExceededError,
    RunIdentifiers,
    SystemClock,
    create_run_context,
)
from core.runtime.agent_loop import (
    ActionOutcome,
    AgentAction,
    AgentLoop,
    AgentLoopDriver,
    AgentLoopPolicy,
    AgentObservation,
    LEGACY_AGENT_ROUTER_STEP_ID,
    LEGACY_AGENT_ROUTER_STEP_NAME,
    LegacyAgentRouterDriver,
)
from core.runtime.model_context import (
    ContextBuilder, ContextBuildRequest, ContextBuildResult, ContextBudgetExceededError, ContextDropRecord,
    ContextItem, ContextSourceType, ContextStats, ContextTrustLevel, DeterministicTokenEstimator,
    MemoryContextRecord, MemoryProvenance, ModelContextRequirements, TokenEstimator,
)
from core.runtime.planning import Plan, PlanSource, PlanStep, PlanValidator, RiskLevel, TaskCapabilityRequirements, create_single_step_plan
from core.runtime.plan_graph import PlanGraph, PlanGraphValidationError, PlanGraphValidator
from core.runtime.model_selection import (ModelCostProfile, ModelPreference, ModelProfile, ModelProfileId, ModelResolver, ModelSelectionDecision, ModelSelectionError, ModelSelectionObjective, ModelSelectionPolicy, ModelSelectionReason, ModelSelectionRequest)
from core.runtime.state_machine import (
    AgentStateMachine,
    InvalidStateTransitionError,
    RunEventType,
    RunStateEvent,
    StepEventType,
    StepStateEvent,
)
from core.runtime.scheduler import (
    SchedulerClaimError,
    SchedulerError,
    SchedulerPlanStateMismatchError,
    SchedulerSnapshot,
    SerialScheduler,
    StepClaim,
)
from core.runtime.run_coordinator import (
    RunCoordinator,
    RunCoordinatorError,
    RunCoordinatorResult,
    RunFinalizationDecision,
)
from core.runtime.events import (
    RUNTIME_EVENT_SCHEMA_VERSION,
    CancellationPayload,
    ErrorPayload,
    ModelCompletedPayload,
    ModelStartedPayload,
    OutputDeltaPayload,
    RunCompletedPayload,
    RunStartedPayload,
    RetrievalBudgetPayload,
    RetrievalCompletedPayload,
    RetrievalStageCompletedPayload,
    RetrievalStartedPayload,
    RuntimeEvent,
    RuntimeEventDraft,
    RuntimeEventPayload,
    RuntimeEventType,
    StepCompletedPayload,
    StepStartedPayload,
    ToolCompletedPayload,
    ToolStartedPayload,
)
from core.runtime.event_channel import (
    EventChannelClosedError,
    EventChannelState,
    RuntimeEventChannel,
)
from core.runtime.event_emitter import (
    EventEmitterSyncError,
    RunEventEmitter,
    StepEventEmitter,
)
from core.runtime.stream_adapter import RuntimeEventTextAdapter

__all__ = [
    "AGENT_STATE_SCHEMA_VERSION",
    "ActionOutcome",
    "AgentAction",
    "AgentLoop",
    "AgentLoopDriver",
    "AgentLoopPolicy",
    "AgentObservation",
    "AgentState",
    "AgentStateMachine",
    "AgentStateValidationError",
    "CancellationSource",
    "CancellationReason", "RunHandle", "RunRegistry", "process_run_registry",
    "OperationTimeoutError", "OperationType", "effective_timeout_seconds",
    "ContextBuilder", "ContextBuildRequest", "ContextBuildResult", "ContextBudgetExceededError",
    "ContextDropRecord", "ContextItem", "ContextSourceType", "ContextStats", "ContextTrustLevel",
    "DeterministicTokenEstimator", "MemoryContextRecord", "MemoryProvenance",
    "ModelContextRequirements", "TokenEstimator",
    "Plan", "PlanSource", "PlanStep", "PlanValidator", "RiskLevel", "TaskCapabilityRequirements", "create_single_step_plan",
    "PlanGraph", "PlanGraphValidationError", "PlanGraphValidator",
    "ModelCostProfile", "ModelPreference", "ModelProfile", "ModelProfileId", "ModelResolver", "ModelSelectionDecision", "ModelSelectionError", "ModelSelectionObjective", "ModelSelectionPolicy", "ModelSelectionReason", "ModelSelectionRequest",
    "CancellationToken",
    "Clock",
    "Deadline",
    "LEGACY_DEFAULT_SESSION_ID",
    "LEGACY_AGENT_ROUTER_STEP_ID",
    "LEGACY_AGENT_ROUTER_STEP_NAME",
    "LegacyAgentRouterDriver",
    "InvalidStateTransitionError",
    "RunCancelledError",
    "RunContext",
    "RunCoordinator",
    "RunCoordinatorError",
    "RunCoordinatorResult",
    "RunContextData",
    "RunDeadlineExceededError",
    "RunIdentifiers",
    "RunStatus",
    "RunEventType",
    "RunStateEvent",
    "RunFinalizationDecision",
    "SchedulerClaimError",
    "SchedulerError",
    "SchedulerPlanStateMismatchError",
    "SchedulerSnapshot",
    "SerialScheduler",
    "StepClaim",
    "StepEventType",
    "StepState",
    "StepStateEvent",
    "StepStatus",
    "StopReason",
    "UnsupportedStateVersionError",
    "RUNTIME_EVENT_SCHEMA_VERSION",
    "CancellationPayload",
    "ErrorPayload",
    "EventChannelClosedError",
    "EventChannelState",
    "EventEmitterSyncError",
    "ModelCompletedPayload",
    "ModelStartedPayload",
    "OutputDeltaPayload",
    "RunCompletedPayload",
    "RunEventEmitter",
    "RunStartedPayload",
    "RetrievalBudgetPayload",
    "RetrievalCompletedPayload",
    "RetrievalStageCompletedPayload",
    "RetrievalStartedPayload",
    "RuntimeEvent",
    "RuntimeEventChannel",
    "RuntimeEventDraft",
    "RuntimeEventPayload",
    "RuntimeEventTextAdapter",
    "RuntimeEventType",
    "StepCompletedPayload",
    "StepEventEmitter",
    "StepStartedPayload",
    "ToolCompletedPayload",
    "ToolStartedPayload",
    "SystemClock",
    "create_run_context",
]

from core.runtime.parallel_execution import (
    ParallelExecutionInfrastructureError, ParallelExecutionReport, ParallelExecutor,
    ParallelFailureMode, ParallelExecutionPolicy, StepConcurrencySpec, StepExecutionDriver, StepExecutionMode,
    StepExecutionOutcome,
)

__all__ += [
    "ParallelExecutionInfrastructureError", "ParallelExecutionReport", "ParallelExecutor",
    "ParallelFailureMode", "ParallelExecutionPolicy", "StepConcurrencySpec", "StepExecutionDriver", "StepExecutionMode",
    "StepExecutionOutcome",
]
from core.runtime.budget import BudgetedModelStream, BudgetExceededError, BudgetLedger, BudgetPolicy, BudgetReservation, BudgetReservationError, BudgetSnapshot, BudgetUsage, RunBudget, UsageSource
from core.runtime.blocking_executor import (
    BlockingExecutorAdmissionTimeout,
    BlockingExecutorClosedError,
    BlockingExecutorNestedSubmissionError,
    BlockingExecutorSnapshot,
    BlockingTaskHandle,
    BlockingTaskKind,
    BlockingTaskRecord,
    BlockingTaskState,
    BlockingTaskWaitState,
    BoundedBlockingExecutor,
    DEFAULT_BLOCKING_MAX_PENDING_TASKS,
    DEFAULT_BLOCKING_MAX_WORKERS,
    process_blocking_executor,
)

__all__ += [
    "BudgetedModelStream",
    "BudgetExceededError",
    "BudgetLedger",
    "BudgetPolicy",
    "BudgetReservation",
    "BudgetReservationError",
    "BudgetSnapshot",
    "BudgetUsage",
    "RunBudget",
    "UsageSource",
    "BlockingExecutorAdmissionTimeout",
    "BlockingExecutorClosedError",
    "BlockingExecutorNestedSubmissionError",
    "BlockingExecutorSnapshot",
    "BlockingTaskHandle",
    "BlockingTaskKind",
    "BlockingTaskRecord",
    "BlockingTaskState",
    "BlockingTaskWaitState",
    "BoundedBlockingExecutor",
    "DEFAULT_BLOCKING_MAX_PENDING_TASKS",
    "DEFAULT_BLOCKING_MAX_WORKERS",
    "process_blocking_executor",
]

from core.runtime.circuit_breaker import (
    CircuitOpenError,
    CircuitPermit,
    CircuitPermitStateError,
    ModelCircuitBreaker,
    ModelCircuitBreakerConfig,
    ModelCircuitBreakerRegistry,
    ModelCircuitBreakerSnapshot,
    ModelCircuitState,
)
from core.runtime.model_routing import (
    ModelFailureCategory,
    ModelRoutingCandidate,
    ModelRoutingDecision,
    ModelRoutingError,
    ModelRoutingPolicy,
    RoutingAdjustment,
)
from core.runtime.model_invocation import (
    CircuitHealthOutcome,
    GeneratorModelAdapter,
    ModelAdapter,
    ModelAdapterInvocationError,
    ModelAdapterResolutionError,
    ModelAdapterResolver,
    ModelAdapterResponse,
    ModelInvocationAttempt,
    ModelInvocationChainError,
    ModelInvocationConfirmationRequired,
    ModelInvocationFailure,
    ModelInvocationResult,
    ModelInvocationRouter,
    ModelUsageSource,
    classify_model_failure,
)
from core.runtime.retry import (
    AsyncioSleeper, CancellableRetrySleeper, JitterMode, OperationIdempotency, RandomSource,
    RateLimitRecoveryMode, RetryDecision, RetryExecutor, RetryPolicy,
    RetryableOperationKind, Sleeper, retry_allowed_by_idempotency,
)
from core.runtime.tool_contract import (
    RetryDisposition, ToolErrorCategory, ToolExecutionError, ToolExecutionPhase,
    ToolExecutionResult, ToolExecutionSpec, ToolExecutionStatus, ToolInvocation,
    ToolOutput, ToolOutputValidationError, ToolSideEffectKind, ToolSideEffectState, build_tool_output,
    canonical_json_digest, retry_disposition_for, safe_key_digest, thaw_json,
)
from core.runtime.tool_concurrency import (
    ToolConcurrencyController, ToolResourceAcquireError, ToolResourceLease,
    ToolWorkerRecord,
)
from core.runtime.tool_adapters import (
    ComplexWorkflowToolAdapter, LegacyStringToolAdapter, ToolAdapter,
    ToolAdapterInvocationError, ToolAdapterResponse,
)
from core.runtime.tool_execution import (
    AttemptSideEffectTracker, ToolAttemptExecutor, ToolExecutionContext,
    ToolExecutionFailed, ToolExecutionService,
)

__all__ += [
    "CircuitHealthOutcome",
    "CircuitOpenError",
    "CircuitPermit",
    "CircuitPermitStateError",
    "GeneratorModelAdapter",
    "ModelAdapter",
    "ModelAdapterInvocationError",
    "ModelAdapterResolutionError",
    "ModelAdapterResolver",
    "ModelAdapterResponse",
    "ModelCircuitBreaker",
    "ModelCircuitBreakerConfig",
    "ModelCircuitBreakerRegistry",
    "ModelCircuitBreakerSnapshot",
    "ModelCircuitState",
    "ModelFailureCategory",
    "ModelInvocationAttempt",
    "ModelInvocationChainError",
    "ModelInvocationConfirmationRequired",
    "ModelInvocationFailure",
    "ModelInvocationResult",
    "ModelInvocationRouter",
    "ModelRoutingCandidate",
    "ModelRoutingDecision",
    "ModelRoutingError",
    "ModelRoutingPolicy",
    "ModelUsageSource",
    "RoutingAdjustment",
    "classify_model_failure",
    "AsyncioSleeper", "CancellableRetrySleeper", "JitterMode", "OperationIdempotency", "RandomSource",
    "RateLimitRecoveryMode", "RetryDecision", "RetryExecutor", "RetryPolicy",
    "RetryableOperationKind", "Sleeper", "retry_allowed_by_idempotency",
    "RetryDisposition", "ToolErrorCategory", "ToolExecutionError", "ToolExecutionPhase",
    "ToolExecutionResult", "ToolExecutionSpec", "ToolExecutionStatus", "ToolInvocation",
    "ToolOutput", "ToolOutputValidationError", "ToolSideEffectKind", "ToolSideEffectState", "build_tool_output",
    "canonical_json_digest", "retry_disposition_for", "safe_key_digest", "thaw_json",
    "ToolConcurrencyController", "ToolResourceAcquireError", "ToolResourceLease",
    "ToolWorkerRecord",
    "ComplexWorkflowToolAdapter", "LegacyStringToolAdapter", "ToolAdapter",
    "ToolAdapterInvocationError", "ToolAdapterResponse",
    "AttemptSideEffectTracker", "ToolAttemptExecutor", "ToolExecutionContext",
    "ToolExecutionFailed", "ToolExecutionService",
]

from core.runtime.retrieval_contract import (
    CitationBinding,
    MaterializedDocument,
    QueryRewriteStrategy,
    RetrievalBudgetUsage,
    RetrievalCandidate,
    RetrievalErrorCategory,
    RetrievalExecutionError,
    RetrievalExecutionResult,
    RetrievalExecutionSpec,
    RetrievalExecutionStatus,
    RetrievalInvocation,
    RetrievalProvenance,
    RetrievalStage,
    RetrievalStageRecord,
    RetrievalStageStatus,
    RetrievalTransformation,
    RetrievedChunk,
    SourceMetadata,
    content_digest,
    normalize_query,
    query_digest,
)
from core.runtime.retrieval_context import (
    RetrievalDeadlineExceededError,
    RetrievalExecutionContext,
)
from core.runtime.retrieval_adapters import (
    QueryEmbedding,
    RetrievalAdapter,
    RetrievalAdapterError,
    RuntimeKnowledgeRetrievalAdapter,
)
from core.runtime.retrieval_execution import RetrievalExecutionService
from core.knowledge_base.vector_scores import (
    VectorScoreSemantics,
    normalize_vector_score,
)

__all__ += [
    "CitationBinding",
    "MaterializedDocument",
    "QueryEmbedding",
    "QueryRewriteStrategy",
    "RetrievalAdapter",
    "RetrievalAdapterError",
    "RetrievalBudgetUsage",
    "RetrievalCandidate",
    "RetrievalDeadlineExceededError",
    "RetrievalErrorCategory",
    "RetrievalExecutionContext",
    "RetrievalExecutionError",
    "RetrievalExecutionResult",
    "RetrievalExecutionService",
    "RetrievalExecutionSpec",
    "RetrievalExecutionStatus",
    "RetrievalInvocation",
    "RetrievalProvenance",
    "RetrievalStage",
    "RetrievalStageRecord",
    "RetrievalStageStatus",
    "RetrievalTransformation",
    "RetrievedChunk",
    "RuntimeKnowledgeRetrievalAdapter",
    "SourceMetadata",
    "content_digest",
    "normalize_query",
    "query_digest",
    "VectorScoreSemantics",
    "normalize_vector_score",
]
