"""wp1 initial canonical persistence schema

Revision ID: 19d1ccbe8526
Revises: 
Create Date: 2026-09-10 18:51:32.693427

Stage6-WP1 baseline: PostgreSQL Canonical Persistence for the four existing
LocalAgent relational domains. Verified against ``core/persistence/models.py``
by re-running autogenerate, which detects zero drift.

Scope notes
-----------
* Only the four existing domains are created here: Runtime Journal, Snapshot,
  Event Consumer Checkpoint, Memory. Tables owned by later work packages
  (users / roles / user_roles / evaluation_jobs / evaluation_results /
  outbox_events / consumer_processed_events) are deliberately NOT created.
* ``runtime_event_journal.safe_payload`` is stored as canonical JSON **text**,
  not jsonb: ``event_digest`` is this table's persisted identity algorithm and
  jsonb key/number normalisation could change the digest source. The Runtime
  contract beats storage convenience here.
* ``long_term_memory`` / ``project_semantic_memory`` use jsonb for ``payload``
  (no digest identity there) so the episodic partial unique indexes can index
  ``payload ->> 'episode_kind'`` directly.
* The SQLite FTS5 external-content table and its three triggers are replaced by
  a PostgreSQL native generated ``tsvector`` column (GIN indexed) on
  ``messages``.
* SQLite ``json_extract`` partial-index predicates become ``jsonb ->>``.
* Terminal uniqueness (at most one ``RUN_COMPLETED`` per run) is enforced in
  the database by a partial unique index, not only by application validation.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '19d1ccbe8526'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('event_consumption_checkpoint',
    sa.Column('consumer_id', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence > 0', name='ck_event_consumption_checkpoint_sequence'),
    sa.PrimaryKeyConstraint('consumer_id', 'event_id'),
    sa.UniqueConstraint('consumer_id', 'run_id', 'sequence', name='uq_event_consumption_checkpoint_progress')
    )
    op.create_index('ix_event_consumption_checkpoint_run', 'event_consumption_checkpoint', ['consumer_id', 'run_id'], unique=False)
    op.create_table('long_term_memory',
    sa.Column('memory_id', sa.String(length=255), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('memory_scope', sa.String(length=64), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logical_key', sa.String(length=512), nullable=True),
    sa.Column('origin_type', sa.String(length=64), nullable=False),
    sa.Column('origin_run_id', sa.String(length=255), nullable=False),
    sa.Column('origin_exchange_id', sa.String(length=255), nullable=False),
    sa.Column('origin_agent_id', sa.String(length=255), nullable=False),
    sa.Column('origin_memory_scope', sa.String(length=64), nullable=False),
    sa.Column('formation_method', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('superseded_by_memory_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('ix_long_term_memory_agent_scope', 'long_term_memory', ['agent_id', 'memory_scope'], unique=False)
    op.create_index('ix_long_term_memory_episodic_active_scope', 'long_term_memory', ['agent_id', 'memory_scope', sa.literal_column('created_at DESC'), sa.literal_column('memory_id ASC')], unique=False, postgresql_where=sa.text("memory_type = 'EPISODIC' AND status = 'ACTIVE'"))
    op.create_index('uq_long_term_memory_episodic_run_identity', 'long_term_memory', ['memory_type', 'origin_run_id'], unique=True, postgresql_where=sa.text("memory_type = 'EPISODIC' AND COALESCE(payload ->> 'episode_kind', 'RUN') = 'RUN'"))
    op.create_index('uq_long_term_memory_episodic_step_identity', 'long_term_memory', ['memory_type', 'origin_run_id', 'agent_id', sa.literal_column("(payload ->> 'origin_step_id')")], unique=True, postgresql_where=sa.text("memory_type = 'EPISODIC' AND payload ->> 'episode_kind' = 'STEP'"))
    op.create_table('message_exchanges',
    sa.Column('exchange_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('memory_scope', sa.String(length=32), server_default=sa.text("'direct'"), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('user_message_id', sa.BigInteger(), nullable=True),
    sa.Column('assistant_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("memory_scope IN ('direct', 'orchestration')", name='ck_message_exchanges_memory_scope'),
    sa.CheckConstraint("state IN ('PENDING', 'COMMITTED')", name='ck_message_exchanges_state'),
    sa.PrimaryKeyConstraint('exchange_id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_exchanges_state', 'message_exchanges', ['state'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('memory_scope', sa.String(length=32), server_default=sa.text("'direct'"), nullable=False),
    sa.Column('exchange_id', sa.String(length=255), nullable=True),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', content)", persisted=True), nullable=True),
    sa.CheckConstraint("memory_scope IN ('direct', 'orchestration')", name='ck_messages_memory_scope'),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_messages_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_agent_scope_time', 'messages', ['agent_id', 'memory_scope', 'timestamp', 'id'], unique=False)
    op.create_index('ix_messages_agent_time', 'messages', ['agent_id', 'timestamp', 'id'], unique=False)
    op.create_index('ix_messages_scope_time', 'messages', ['memory_scope', 'timestamp', 'id'], unique=False)
    op.create_index('ix_messages_search_vector', 'messages', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_messages_timestamp', 'messages', ['timestamp', 'id'], unique=False)
    op.create_index('uq_messages_exchange_role', 'messages', ['exchange_id', 'role'], unique=True, postgresql_where=sa.text('exchange_id IS NOT NULL'))
    op.create_table('project_semantic_memory',
    sa.Column('memory_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('owner_kind', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=False),
    sa.Column('logical_key', sa.String(length=512), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('origin_agent_id', sa.String(length=255), nullable=False),
    sa.Column('origin_run_id', sa.String(length=255), nullable=False),
    sa.Column('created_by_agent_id', sa.String(length=255), nullable=False),
    sa.Column('updated_by_agent_id', sa.String(length=255), nullable=False),
    sa.Column('source_memory_id', sa.String(length=255), nullable=True),
    sa.Column('source_owner_agent_id', sa.String(length=255), nullable=True),
    sa.Column('promoted_by_agent_id', sa.String(length=255), nullable=True),
    sa.Column('promotion_run_id', sa.String(length=255), nullable=True),
    sa.Column('promotion_time', sa.Text(), nullable=True),
    sa.Column('superseded_by_memory_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('ix_project_semantic_active_scope', 'project_semantic_memory', ['project_id', 'logical_key', sa.literal_column('created_at DESC'), sa.literal_column('memory_id ASC')], unique=False, postgresql_where=sa.text("visibility = 'PROJECT' AND status = 'ACTIVE'"))
    op.create_index('ix_project_semantic_partition', 'project_semantic_memory', ['project_id', 'logical_key', sa.literal_column('created_at ASC'), sa.literal_column('memory_id ASC')], unique=False)
    op.create_table('runtime_event_journal',
    sa.Column('journal_schema_version', sa.Integer(), nullable=False),
    sa.Column('event_schema_version', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('emitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('journaled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('step_id', sa.String(length=255), nullable=True),
    sa.Column('step_sequence', sa.Integer(), nullable=True),
    sa.Column('span_id', sa.String(length=255), nullable=True),
    sa.Column('parent_span_id', sa.String(length=255), nullable=True),
    sa.Column('safe_payload', sa.Text(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('event_digest', sa.String(length=64), nullable=False),
    sa.CheckConstraint('event_schema_version > 0', name='ck_runtime_event_journal_event_schema_version'),
    sa.CheckConstraint('journal_schema_version > 0', name='ck_runtime_event_journal_journal_schema_version'),
    sa.CheckConstraint('sequence > 0', name='ck_runtime_event_journal_sequence'),
    sa.CheckConstraint('step_id IS NOT NULL OR step_sequence IS NULL', name='ck_runtime_event_journal_step_pairing'),
    sa.PrimaryKeyConstraint('run_id', 'sequence'),
    sa.UniqueConstraint('event_id', name='uq_runtime_event_journal_event_id')
    )
    op.create_index('ix_runtime_event_journal_run_type', 'runtime_event_journal', ['run_id', 'event_type'], unique=False)
    op.create_index('uq_runtime_event_journal_terminal_per_run', 'runtime_event_journal', ['run_id'], unique=True, postgresql_where=sa.text("event_type = 'RUN_COMPLETED'"))
    op.create_table('runtime_snapshots',
    sa.Column('snapshot_schema_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.CheckConstraint('snapshot_schema_version > 0', name='ck_runtime_snapshots_schema_version'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index('ix_runtime_snapshots_run_created', 'runtime_snapshots', ['run_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runtime_snapshots_run_created', table_name='runtime_snapshots')
    op.drop_table('runtime_snapshots')
    op.drop_index('uq_runtime_event_journal_terminal_per_run', table_name='runtime_event_journal', postgresql_where=sa.text("event_type = 'RUN_COMPLETED'"))
    op.drop_index('ix_runtime_event_journal_run_type', table_name='runtime_event_journal')
    op.drop_table('runtime_event_journal')
    op.drop_index('ix_project_semantic_partition', table_name='project_semantic_memory')
    op.drop_index('ix_project_semantic_active_scope', table_name='project_semantic_memory', postgresql_where=sa.text("visibility = 'PROJECT' AND status = 'ACTIVE'"))
    op.drop_table('project_semantic_memory')
    op.drop_index('uq_messages_exchange_role', table_name='messages', postgresql_where=sa.text('exchange_id IS NOT NULL'))
    op.drop_index('ix_messages_timestamp', table_name='messages')
    op.drop_index('ix_messages_search_vector', table_name='messages', postgresql_using='gin')
    op.drop_index('ix_messages_scope_time', table_name='messages')
    op.drop_index('ix_messages_agent_time', table_name='messages')
    op.drop_index('ix_messages_agent_scope_time', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_exchanges_state', table_name='message_exchanges')
    op.drop_table('message_exchanges')
    op.drop_index('uq_long_term_memory_episodic_step_identity', table_name='long_term_memory', postgresql_where=sa.text("memory_type = 'EPISODIC' AND payload ->> 'episode_kind' = 'STEP'"))
    op.drop_index('uq_long_term_memory_episodic_run_identity', table_name='long_term_memory', postgresql_where=sa.text("memory_type = 'EPISODIC' AND COALESCE(payload ->> 'episode_kind', 'RUN') = 'RUN'"))
    op.drop_index('ix_long_term_memory_episodic_active_scope', table_name='long_term_memory', postgresql_where=sa.text("memory_type = 'EPISODIC' AND status = 'ACTIVE'"))
    op.drop_index('ix_long_term_memory_agent_scope', table_name='long_term_memory')
    op.drop_table('long_term_memory')
    op.drop_index('ix_event_consumption_checkpoint_run', table_name='event_consumption_checkpoint')
    op.drop_table('event_consumption_checkpoint')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
