apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localagent-stage6-wp8
resources:
  - ../base
  - infrastructure.yaml
patches:
  - path: namespace-patch.yaml
images:
  - name: localagent
    newName: localagent
    newTag: stage6-wp8
